plugins {
	id 'net.fabricmc.fabric-loom' version '1.17.+'
	id 'maven-publish'
	id 'checkstyle'
}

base {
	archivesName = project.archives_base_name
}

version = "$project.mod_version+$project.minecraft_version"
group = project.maven_group

sourceSets {
	javadoc {
	}

	testMod {
		compileClasspath += main.compileClasspath
		runtimeClasspath += main.runtimeClasspath
	}
}

loom {
	runs {
		testModClient {
			client()
			name = 'Test Mod Client'
			source sourceSets.testMod
		}

		testModServer {
			server()
			name = 'Test Mod Server'
			source sourceSets.testMod
		}
	}
}

repositories {
	maven {
		url = "https://staging.alexiil.uk/maven/"
		content {
			includeGroup "io.github.cottonmc"
		}
	}
	maven {
		url = "https://maven.terraformersmc.com/releases"
		content {
			includeGroup "com.terraformersmc"
		}
	}
}

dependencies {
	minecraft "com.mojang:minecraft:${project.minecraft_version}"
	implementation "net.fabricmc:fabric-loader:${project.loader_version}"

	// True: module classes are used in public API classes/methods/fields
	def fabricApiModules = [
			'fabric-api-base': true,
			'fabric-lifecycle-events-v1': false,
			'fabric-networking-api-v1': true,
			'fabric-rendering-v1': false,
			'fabric-resource-loader-v1': false,
	]
	fabricApiModules.forEach { module, isApi ->
		def dependency = fabricApi.module(module, project.fabric_version)

		if (isApi) {
			api dependency
		} else {
			implementation dependency
		}
	}

	implementation "io.github.cottonmc:Jankson-Fabric:${project.jankson_version}"
	include "io.github.cottonmc:Jankson-Fabric:${project.jankson_version}"

	include api("io.github.juuxel:libninepatch:${project.libninepatch_version}")

	compileOnly("com.terraformersmc:modmenu:$project.modmenu_version") {
		exclude group: 'net.fabricmc.fabric-api'
		exclude group: 'net.fabricmc', module: 'fabric-loader'
	}

	// Test mod dependencies
	testModImplementation sourceSets.main.output
	testModImplementation "net.fabricmc.fabric-api:fabric-api:${project.fabric_version}"
	// modTestModRuntimeOnly("com.terraformersmc:modmenu:$project.modmenu_version") {
	// 	exclude group: 'net.fabricmc.fabric-api'
	// 	exclude group: 'net.fabricmc', module: 'fabric-loader'
	// }
}

processResources {
	inputs.property "version", project.version

	filesMatching("fabric.mod.json") {
		expand "version": project.version
	}
}

java {
	withSourcesJar()
	withJavadocJar()

	sourceCompatibility = JavaVersion.VERSION_25
	targetCompatibility = JavaVersion.VERSION_25
}

tasks.withType(JavaCompile) {
	// ensure that the encoding is set to UTF-8, no matter what the system default is
	// this fixes some edge cases with special characters not displaying correctly
	// see http://yodaconditions.net/blog/fix-for-java-file-encoding-problems-with-gradle.html
	options.encoding = "UTF-8"
	options.release = 25
}

jar {
	from "CREDITS.txt", "LICENSE"
}

checkstyle {
	configFile = rootProject.file('checkstyle.xml')
	configProperties = [suppressions: rootProject.file('checkstyle.suppressions.xml').absolutePath]
	toolVersion = '10.9.2'
}

def javadocBuildJar = tasks.register('javadocBuildJar', Jar) {
	destinationDirectory = file('build/devlibs')
	archiveClassifier = 'javadoc-build'
	from sourceSets.javadoc.output
}

javadoc {
	dependsOn javadocBuildJar

	options {
		links 'https://javadoc.io/doc/org.jspecify/jspecify/1.0.0'
		links 'https://javadoc.io/doc/org.jetbrains/annotations/26.0.2'
		links "https://maven.fabricmc.net/docs/fabric-api-$project.fabric_version/"
		taglets 'io.github.cottonmc.cotton.gui.jd.ExperimentalTaglet',
				'io.github.cottonmc.cotton.gui.jd.PropertyTaglet'
		tagletPath javadocBuildJar.get().archiveFile.get().asFile
	}

	exclude("**/impl/**")
}

// configure the maven publication
publishing {
	publications {
		maven(MavenPublication) {
			from components.java
			pom {
				name = "LibGui"
				description = "Minecraft GUI Library"
				url = "https://github.com/CottonMC/LibGui"
				licenses {
					license {
						name = "MIT"
						url = "https://github.com/CottonMC/LibGui/blob/HEAD/LICENSE"
					}
				}
				developers {
					developer {
						name = "CottonMC"
						url = "https://github.com/CottonMC"
					}
				}
			}
		}
	}

	// select the repositories you want to publish to
	repositories {
		def env = System.getenv()
		if (env.MAVEN_URL) {
			maven {
				url = env.MAVEN_URL
				credentials {
					username = env.MAVEN_USERNAME
					password = env.MAVEN_PASSWORD
				}
			}
		}
	}
}
