# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G

# Fabric Properties
# check these on https://fabricmc.net/develop
	minecraft_version=26.2
	loader_version=0.19.3

# Mod Properties
	mod_version = 17.0.0
	maven_group = io.github.cottonmc
	archives_base_name = LibGui

# Dependencies
	fabric_version=0.152.1+26.2
	jankson_version=13.0.0+j1.2.3
	modmenu_version=20.0.0-beta.2
	libninepatch_version=1.2.0
